---
kind: Secret
apiVersion: v1
metadata:
  name: network-infra-viewer-auth
  namespace: network-infra-viewer
type: Opaque
data:
  APP_SECRET_KEY: dGZHOHZIZ1BzZGZkZ2dUem9yZUp0MldsTWp1OENlSXdWSDRiUAo=

