---
kind: Secret
apiVersion: v1
metadata:
  name: network-infra-viewer-auth
  namespace: network-infra-viewer
type: Opaque
data:
  APP_SECRET_KEY: dGZHOHZIZ1BzZGZkZ2dUem9yZUp0MldsTWp1OENlSXdWSDRiUAo=
  AUTHENTIK_CLIENT_ID: bGtzZGFmanNkZmthamtzYmRmZXJhc2dkZmdzZGZnCg==
  AUTHENTIK_CLIENT_SECRET: bGtzZGFmanNkZmthamtzYmRmZXJhc2dkZmdzZGZnCg==
  KEYCLOAK_CLIENT_ID: bmV0d29yay1pbmZyYXN0cnVjdHVyZS12aWV3ZXI=
  KEYCLOAK_CLIENT_SECRET: MEV5REtrVVlGUG56RnZYSFBrM1NwcnJwRlVDQlFJT1M=