---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: network-infra-viewer-pv
  labels:
    type: local
    app: webserver
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/home/ubuntu/data/"
